# Generated by Django 6.0.2 on 2026-04-22 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_full_name_userprofile_location_and_more'),
        ('documents', '0002_proposal_job_proposal_status_alter_proposal_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='email_address',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='cv',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cv',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cv',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cv',
            name='portfolio_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cv',
            name='professional_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cv',
            name='professional_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cv',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='cvs', to='accounts.skill'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='ats_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cv',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='CVEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('graduation_year', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='documents.cv')),
            ],
        ),
        migrations.CreateModel(
            name='CVExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False)),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='documents.cv')),
            ],
        ),
    ]
