# Generated by Django 6.0.2 on 2026-05-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_cv_email_address_cv_full_name_cv_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
    ]
