# Generated by Django 6.0.2 on 2026-05-02 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_cv_is_base'),
        ('opportunities', '0004_job_required_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opportunities.job'),
        ),
    ]
