# Generated by Django 6.0.2 on 2026-04-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_full_name_userprofile_location_and_more'),
        ('opportunities', '0003_alter_freelanceproject_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='accounts.skill'),
        ),
    ]
