# Generated by Django 6.0.2 on 2026-04-25 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_matchresult_ai_tips_matchresult_matched_skills_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchresult',
            options={'ordering': ['-match_score']},
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='match_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
