# Generated by Django 6.0.2 on 2026-04-25 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_alter_matchresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchresult',
            options={'ordering': ['-match_score', '-created_at']},
        ),
    ]
